# Generated by Django 5.0.4 on 2024-05-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("address", models.CharField(max_length=255)),
                ("grade", models.CharField(max_length=10)),
                ("major", models.CharField(max_length=100)),
            ],
        ),
    ]
